# Generated by Django 5.1.6 on 2025-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0030_alter_review_google_rating'),
        ('blog', '0009_author_picture_alt_description'),
        ('guide', '0003_travelguideregion_activities_travelguideregion_blogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguideregion',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='guide_region', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='travelguideregion',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='guide_region', to='blog.post'),
        ),
    ]
