# Generated by Django 5.1.6 on 2025-06-30 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_travelguideregion_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionWeatherPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(help_text='e.g. Jun–Aug', max_length=50)),
                ('start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
                ('end_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
                ('high_temp', models.IntegerField(help_text='High temperature (°C)')),
                ('low_temp', models.IntegerField(help_text='Low temperature (°C)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_periods', to='guide.travelguideregion')),
            ],
            options={
                'unique_together': {('region', 'period_name')},
            },
        ),
    ]
