# Generated by Django 5.1.6 on 2025-06-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_regionweatherperiod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionweatherperiod',
            unique_together={('region', 'start_month', 'end_month')},
        ),
        migrations.AlterField(
            model_name='regionweatherperiod',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_periods', to='guide.travelguideregion'),
        ),
        migrations.RemoveField(
            model_name='regionweatherperiod',
            name='period_name',
        ),
    ]
