# Generated by Django 5.1.6 on 2025-06-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_alter_regionweatherperiod_high_temp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionweatherperiod',
            unique_together=set(),
        ),
    ]
