# Generated by Django 5.1.6 on 2025-06-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author_picture_alt_description'),
        ('guide', '0008_alter_regionweatherperiod_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguide',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.author'),
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='guide_category',
        ),
        migrations.DeleteModel(
            name='GuideAuthour',
        ),
        migrations.DeleteModel(
            name='TravelGuideCategory',
        ),
    ]
