# Generated by Django 5.1.6 on 2025-06-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_alter_travelguide_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionweatherperiod',
            name='end_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regionweatherperiod',
            name='start_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True),
        ),
    ]
