# Generated by Django 5.1.6 on 2025-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_alter_regionweatherperiod_end_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelguide',
            options={},
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='guide_duration_to_read',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='name',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='title',
        ),
        migrations.RemoveField(
            model_name='travelguide',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='thumbnail_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
