# Generated by Django 5.1.6 on 2025-07-06 11:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_alter_travelguide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguideregion',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
