# Generated by Django 5.1.6 on 2025-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_activitycategory_content_activityregion_content'),
        ('blog', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='posts', to='activity.activity'),
        ),
    ]
