# Generated by Django 5.1.6 on 2025-02-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='activities',
            new_name='related_activities',
        ),
    ]
