# Generated by Django 5.1.6 on 2025-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_activities_post_related_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture_alt_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
