# Generated by Django 4.1.4 on 2023-02-07 07:28

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='about',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
