# Generated by Django 4.1.4 on 2023-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teammember_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='type',
            field=models.CharField(choices=[('Executive Team', 'Executive Team'), ('Representative', 'Representative'), ('Trekking Guides', 'Trekking Guides'), ('Tour Guide', 'Tour Guide')], default='Representative', max_length=300),
        ),
    ]
