# Generated by Django 4.1.4 on 2023-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_photo_testimonial_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link_to_website', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link_to_website', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_line1', models.CharField(default='Line 1', max_length=328)),
                ('hero_title_line2', models.CharField(default='Line 2', max_length=328)),
                ('hero_title_line3', models.CharField(default='Line 3', max_length=328)),
                ('hero_section_subtitle', models.CharField(default='Discover The Best Hiking Trails And Bee-Watching Spots On Your Next Adventure. Book A Trip Now', max_length=328)),
                ('hero_section_image', models.ImageField(blank=True, upload_to='')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.DeleteModel(
            name='HeroSectionContent',
        ),
    ]
