# Generated by Django 4.1.4 on 2023-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_affiliations_partners_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_section_subtitle',
            field=models.TextField(default='Discover The Best Hiking Trails And Bee-Watching Spots On Your Next Adventure. Book A Trip Now'),
        ),
    ]
