# Generated by Django 4.1.4 on 2023-02-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_siteconfiguration_hero_section_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='maintenance_mode',
        ),
    ]
