# Generated by Django 4.1.4 on 2023-01-20 05:18

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('activity_title', models.CharField(max_length=300)),
                ('activity_location', models.CharField(max_length=300)),
                ('contact_person_name', models.CharField(max_length=300)),
                ('contact_person_phone', models.CharField(max_length=300)),
                ('activity_duration', models.CharField(max_length=300)),
                ('activity_price', models.CharField(default=0, max_length=300)),
                ('activity_description', django_summernote.fields.SummernoteTextField()),
                ('activity_highlights', django_summernote.fields.SummernoteTextField()),
                ('activity_includes', django_summernote.fields.SummernoteTextField()),
                ('activity_excludes', django_summernote.fields.SummernoteTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True)),
                ('thumnail_image', models.ImageField(blank=True, upload_to='')),
                ('thumnail_image_alt_description', models.CharField(default='Alt Description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination_detail', django_summernote.fields.SummernoteTextField(blank=True)),
                ('thumnail_image', models.ImageField(blank=True, upload_to='')),
                ('thumnail_image_alt_description', models.CharField(default='Alt Description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_itineary_title', models.CharField(max_length=500)),
                ('activity_itineary_description', models.TextField(max_length=128)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityitenary', to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_alt_description', models.CharField(default='Image Description', max_length=428)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityimage', to='activity.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.activitycategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.destination'),
        ),
    ]
