# Generated by Django 4.1.4 on 2023-02-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_small_detail',
            field=models.TextField(blank=True),
        ),
    ]
