# Generated by Django 5.1.6 on 2025-03-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_activitycategory_content_activityregion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='banner_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
