# Generated by Django 5.1.6 on 2025-03-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_activity_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
