# Generated by Django 5.1.6 on 2025-03-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_activity_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('thumbnail_image', models.FileField(upload_to='')),
                ('thumbnail_image_alt_description', models.CharField(default='Image Description', max_length=428)),
                ('video_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('subtitle', models.CharField(max_length=400)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=400)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons_bookings', to='activity.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityBookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons', to='activity.activitybooking')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.addons')),
            ],
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='add_ons',
            field=models.ManyToManyField(blank=True, null=True, through='activity.ActivityBookingAddOn', to='activity.addons'),
        ),
    ]
