# Generated by Django 5.1.6 on 2025-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_videoreview_addons_activitybookingaddon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybooking',
            name='add_ons',
            field=models.ManyToManyField(blank=True, through='activity.ActivityBookingAddOn', to='activity.addons'),
        ),
    ]
