# Generated by Django 5.1.6 on 2025-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_alter_activitybooking_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='subtitle',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
