# Generated by Django 5.1.6 on 2025-03-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_alter_addons_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreview',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='thumbnail_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='thumbnail_image_alt_description',
            field=models.CharField(blank=True, default='Image Description', max_length=428, null=True),
        ),
    ]
