# Generated by Django 5.1.6 on 2025-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_activity_related_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='per_day_walk',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
