# Generated by Django 5.1.6 on 2025-04-03 08:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_activity_per_day_walk'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='add_on_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
