# Generated by Django 5.1.6 on 2025-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_activity_add_on_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_advisor_review', models.IntegerField(blank=True, null=True)),
                ('google_review', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
