# Generated by Django 5.1.6 on 2025-08-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0030_alter_review_google_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='itinerary_images/')),
                ('image_alt_description', models.CharField(blank=True, default='Image Description', max_length=428, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activity.itineraryactivity')),
            ],
        ),
    ]
