# Generated by Django 5.1.6 on 2025-08-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0031_itineraryimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryimages',
            name='image_alt_description',
        ),
    ]
