# Generated by Django 5.1.6 on 2025-08-17 09:32

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_remove_itineraryimages_image_alt_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tiles', to='activity.activity')),
            ],
        ),
    ]
