# Generated by Django 5.1.6 on 2025-08-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_additionaltiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaltiles',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
