# Generated by Django 5.1.6 on 2025-08-17 09:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0034_alter_additionaltiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaltiles',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
