# Generated by Django 5.1.6 on 2025-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0035_alter_additionaltiles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryimages',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='itinerary', to='activity.itineraryimages'),
        ),
    ]
