# Generated by Django 5.1.6 on 2025-08-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0036_remove_itineraryimages_itinerary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfaq',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
