# Generated by Django 5.1.6 on 2025-08-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0037_alter_activityfaq_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryactivity',
            name='images',
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to='itinerary_images/'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_1_alt_description',
            field=models.CharField(blank=True, default='Image Description', max_length=428, null=True),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to='itinerary_images/'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_2_alt_description',
            field=models.CharField(blank=True, default='Image Description', max_length=428, null=True),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to='itinerary_images/'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_3_alt_description',
            field=models.CharField(blank=True, default='Image Description', max_length=428, null=True),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to='itinerary_images/'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='image_4_alt_description',
            field=models.CharField(blank=True, default='Image Description', max_length=428, null=True),
        ),
        migrations.DeleteModel(
            name='ItineraryImages',
        ),
    ]
