# Generated by Django 5.1.6 on 2025-08-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0038_remove_itineraryactivity_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryactivity',
            name='image_1_alt_description',
            field=models.CharField(blank=True, max_length=428, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='image_2_alt_description',
            field=models.CharField(blank=True, max_length=428, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='image_3_alt_description',
            field=models.CharField(blank=True, max_length=428, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='image_4_alt_description',
            field=models.CharField(blank=True, max_length=428, null=True),
        ),
    ]
