# Generated by Django 5.1.6 on 2025-12-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0039_alter_itineraryactivity_image_1_alt_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregion',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
