# Generated by Django 5.1 on 2025-12-31 10:01

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_activityregion_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='activityfaq',
            options={'ordering': ['order', 'category', 'created_at'], 'verbose_name_plural': 'Activity FAQs'},
        ),
        migrations.AddField(
            model_name='activityfaq',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='faqs', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activityfaq',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityfaq',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_faqs', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='activityfaq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='activityfaq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='activityfaq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='activity.faqcategory'),
        ),
    ]
