# Generated by Django 5.1 on 2025-12-31 10:01

from django.db import migrations


def transfer_link_data(apps, schema_editor):
    ActivityFAQ = apps.get_model("activity", "ActivityFAQ")
    FAQCategory = apps.get_model("activity", "FAQCategory")

    # Create General category
    general_category, _ = FAQCategory.objects.get_or_create(
        name="General", defaults={"slug": "general", "active": True}
    )

    for faq in ActivityFAQ.objects.all():
        # Copy link if it exists
        if faq.activity:
            faq.activities.add(faq.activity)

        # Assign to General category if no category
        if not faq.category:
            faq.category = general_category
            faq.save()


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0041_faqcategory_alter_activityfaq_options_and_more"),
    ]

    operations = [
        migrations.RunPython(transfer_link_data),
    ]
