# Generated by Django 5.1 on 2025-12-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0042_transfer_faq_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityfaq',
            name='activity',
        ),
    ]
