# Generated by Django 5.1 on 2025-12-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0043_remove_activityfaq_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityfaq',
            options={'ordering': ['category__order', 'order', 'created_at'], 'verbose_name_plural': 'Activity FAQs'},
        ),
    ]
