# Generated by Django 5.1.6 on 2026-01-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0044_alter_activityfaq_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQCategory',
            new_name='ActivityFAQCategory',
        ),
    ]
